;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.DamageCue",DevComment="")
+GameplayTagList=(Tag="MiniGame.DoubleJump.CoolDown",DevComment="")
+GameplayTagList=(Tag="MiniGame.GameMode.ScreenMode",DevComment="")
+GameplayTagList=(Tag="MiniGame.Skill",DevComment="")

